AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Scenario 1 Monolithic AWS Lambda — Version_18 (Customer Version 18)

Globals:
  Function:
    Timeout: 10
    MemorySize: 256
    Runtime: nodejs18.x

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: js-lambda-cv-18
      CodeUri: dist/
      Handler: handler.handler
      Events:
        ProxyApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        RootApi:
          Type: Api
          Properties:
            Path: /
            Method: ANY
